In [21]:
import numpy as np
a = [[[1,2],
      [3,4]],
     [[5,6],
     [7,8]]]

In [22]:
a


[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [23]:
np.shape(a)

(2, 2, 2)

In [24]:
a[:]

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [25]:
a[0:1]

[[[1, 2], [3, 4]]]

In [29]:
b = np.array(a)
b[:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
b[:,0]

array([[1, 2],
       [5, 6]])

In [32]:
b[:,1]

array([[3, 4],
       [7, 8]])

In [33]:
b[:,:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [35]:
b[:,:,:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
b[-1]

array([[5, 6],
       [7, 8]])

In [37]:
b[:,-1]

array([[3, 4],
       [7, 8]])

In [39]:
b[:,:,-1]

array([[2, 4],
       [6, 8]])

In [ ]:
b[:]=[]