In [3]:
import numpy as np
import cv2
from PIL import Image
# Create a black image
img = np.zeros((512,512,3), np.uint8)

# Draw a diagonal blue lin with thickness of 5 px
# image, start, end, color, thickness
img = cv2.line(img,(0,0),(511,511),(255,0,0),5)

# To draw a rectangle, you need top-left corner and bottom-right corner of rectangle. 
# This time we will draw a green rectangle at the top-right corner of image.
# image, start, end, color, thickness
img = cv2.rectangle(img,(384,0),(510,128),(0,255,0),3)

# image, center coordinate, radius, color, thickness(-1 fills with color)
img = cv2.circle(img,(447,63), 63, (0,0,255), -1)

# image, center coordinate, axis length(major, minor), rotation angle, start angle, end angle,color, thickness, linetype, shift
img = cv2.ellipse(img,(256,256),(100,50),0,0,180,255,-1)

pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
print(pts, np.shape(pts))
pts = pts.reshape((-1,1,2))
print(pts, np.shape(pts))
# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]
img = cv2.polylines(img,[pts],True,(0,255,255))

font = cv2.FONT_HERSHEY_SIMPLEX
# cv2.putText(image, text, org, font, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])
# org: It is the coordinates of the bottom-left corner of the text string in the image. 
# The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).
cv2.putText(img,'OpenCV',(10,500), font, 4,(255,255,255),2,cv2.LINE_AA)

img = Image.fromarray(img, 'RGB')
img.show()

print(np.shape(img))

open_cv_image = np.array(img) 
print(np.shape(open_cv_image))
print(open_cv_image)

# Convert RGB to BGR 
open_cv_image = open_cv_image[:, :, ::-1].copy() 
cv2.imshow("frame", open_cv_image)

[[10  5]
 [20 30]
 [70 20]
 [50 10]] (4, 2)
[[[10  5]]

 [[20 30]]

 [[70 20]]

 [[50 10]]] (4, 1, 2)
(512, 512, 3)
(512, 512, 3)
[[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]


In [4]:


cv2.destroyAllWindows()