In [1]:
import numpy as np

a = np.empty([2,3,4])

In [2]:
print(a)

[[[1.39265090e-316 0.00000000e+000 3.60440373e+228 3.81998052e+180]
  [7.73400186e-313 8.18434960e-085 5.81821776e+180 5.58802404e-268]
  [2.00429134e-313 3.81674046e-308 1.33360303e+241 1.70820661e-310]]

 [[1.93676345e-282 1.57989218e-313 3.39953911e-308 1.33360301e+241]
  [1.38226806e-310 3.06836125e+257 8.73990005e+245 1.19481439e-298]
  [1.09421345e-303 2.44572280e-260 8.20437588e-304 1.05566968e+015]]]


In [4]:
print(a.shape)

(2, 3, 4)


[[[1.39265090e-316 0.00000000e+000 3.60440373e+228 3.81998052e+180]
  [7.73400186e-313 8.18434960e-085 5.81821776e+180 5.58802404e-268]
  [2.00429134e-313 3.81674046e-308 1.33360303e+241 1.70820661e-310]]

 [[1.93676345e-282 1.57989218e-313 3.39953911e-308 1.33360301e+241]
  [1.38226806e-310 3.06836125e+257 8.73990005e+245 1.19481439e-298]
  [1.09421345e-303 2.44572280e-260 8.20437588e-304 1.05566968e+015]]]
